import { sanitizeAssetPath, sanitizeCssColor, sanitizeThemeCss } from './sanitize';
import type { Theme } from '@/types/database';

/**
 * Generates css/theme.css for the active seasonal theme.
 *
 * Lives in its own module — with no `server-only` import — so the one-time
 * migration script can call it too. Both the migration and the publish
 * pipeline MUST produce identical bytes for the same theme, otherwise the
 * first publish after migration reports a spurious change.
 */
export function renderThemeCss(theme: Theme | null): string {
  const header =
    '/* Generated by the Club America admin dashboard. Do not edit by hand — */\n' +
    '/* changes here are overwritten on the next publish. Edit themes in the  */\n' +
    '/* dashboard under Themes.                                              */\n';

  if (!theme || theme.key === 'normal') {
    return `${header}\n/* Theme: Normal — no overrides, the site uses css/style.css as designed. */\n`;
  }

  const vars: string[] = [];
  const push = (name: string, value: string | null) => {
    const safe = sanitizeCssColor(value);
    if (safe) vars.push(`  ${name}: ${safe};`);
  };

  push('--theme-primary', theme.primary_color);
  push('--theme-secondary', theme.secondary_color);
  push('--theme-accent', theme.accent_color);
  push('--theme-bg', theme.background_color);
  push('--theme-text', theme.text_color);

  const parts = [header, `\n/* Theme: ${theme.name.replace(/[*/]/g, '')} */\n`];

  if (vars.length > 0) {
    parts.push(`:root[data-theme="${cssIdent(theme.key)}"] {\n${vars.join('\n')}\n}\n`);
  }

  const logo = sanitizeAssetPath(theme.logo_path);
  if (logo) {
    parts.push(
      `\n:root[data-theme="${cssIdent(theme.key)}"] .nav__brand img,\n` +
        `:root[data-theme="${cssIdent(theme.key)}"] .hero__seal {\n` +
        `  content: url("${logo}");\n}\n`
    );
  }

  const extra = sanitizeThemeCss(theme.extra_css);
  if (extra) {
    parts.push(`\n/* Custom CSS */\n${extra}\n`);
  }

  return parts.join('');
}

/** Restricts a theme key to characters that are safe inside a CSS selector. */
function cssIdent(value: string): string {
  return value.replace(/[^a-z0-9_-]/gi, '');
}
